#' @title Irreductibility of the Skeleton Matrix
#'
#' @description
#' Tests the irreductibility of the Skeleton Transition Matrix
#'
#' @param M A binary square matrix generated by \link{generate_skeleton} or \link{skel_matrix}.
#' @param ReturnMatrix Do you want Q to be returned? Defaults to FALSE. See Details.
#'
#' @details
#' A skeleton of order \eqn{k} will result in a transition matrix \eqn{M_{2^k\times 2^k}}.
#'
#' M is irreductible if
#' \deqn{\forall i,j \in [1,2^k], \exists n \in ℕ | M^n[i,j]>0}
#' In practice this can be tested with \eqn{n = 1,...,2^k-1}.\deqn{Q[i,j] = \mathcal{I}\{(\sum_{l=1}^{2^k}M^l)[i,j]>0\}}
#'
#' @return Either a logical result for irreductibility or a list containing the result and Q.
#'
#' @export
irreductible = function(M, ReturnMatrix = FALSE){
  stopifnot(ncol(M)==nrow(M))
  Q = M
  M_prod = M
  k = ncol(M)

  for(i in 2:k){
    M_prod = M_prod%*%M
    Q = Q+M_prod
  }

  Q = ifelse(Q>0,1,0)
  irreduc = all(Q==matrix(1,k,k))
  if(ReturnMatrix) return(list(irred = irreduc, Q = Q))
  else return(irreduc)
}
