#' @title Irreductibility of the Skeleton Matrix
#'
#' @description
#' Tests the irreductibility of the Skeleton Transition Matrix
#'
#' @param M A binary square matrix generated by \link{generate_skeleton} or \link{skel_matrix}.
#'
#' @details
#' A skeleton of order \eqn{k} will result in a transition matrix \eqn{M_{2^k\times 2^k}}.
#'
#' M is irreductible if
#' \deqn{\forall i,j \in [1,2^k], \exists n \in ℕ | M^n[i,j]>0}
#' In practice this can be tested with \eqn{n = 1,...,2^k-1}.\deqn{Q[i,j] = \mathcal{I}\{(\sum_{l=1}^{2^k}M^l)[i,j]>0\}}
#'
#' @return Logical result for irreductibility.
#'
#' @export
irreductible = function(M){
  stopifnot(ncol(M)==nrow(M))
  if(any(apply(M, 2, function(J) sum(J)==0))) return(FALSE)
  Q = M
  M_prod = M
  k = ncol(M)

  for(i in 2:k){
    M_prod = M_prod%*%M
    Q = Q+M_prod
    if(all(Q>0)){
      print(paste("All transitions possible after", i, "steps or less"))
      return(TRUE)
    }
  }
  irreduc = all(Q>0)
  return(irreduc)
}
