#' @title Skeleton pruning
#'
#' @description
#' Prunes a probability tree generated by \link{startskel}. Made for \link{generate_skeleton}.
#'
#' @inheritParams generate_skeleton
#' @param t tree.
#' @param copy Set to TRUE to preserve the original tree. FALSE will alter the original tree and not return anything, the default.
#' @param print If TRUE prints how many nodes are cut by level of the tree.
#'
#' @details
#' For a node w, whose children are leaves, removes the children if:
#'  - both don't have enough occurrences to be significant.
#'  - both have no prohibited transitions.
#'  - both have the same prohibited transitions (really should never happen).
#'
#' Starts from the second to last level of the tree.
#'
#' @export

sculptskeleton = function(t, Nmin, copy = F, print=F){
  if(copy) tree = Clone(t)
  else tree = t
  nodes = Traverse(tree, 'level')
  levels = sapply(nodes, function(x) x$level)
  k = tree$height
  for(l in rev(1:(k-1))){
    nds = nodes[levels==l]
    to_trim = nds[sapply(nds, function(x) shouldyoucut(x, 'dom', Nmin))]
    if(print) print(paste(length(to_trim)*2, 'nodos serão removidos',sep=' '))
    lapply(to_trim, FUN = killchildren)
  }
  if(copy) return(tree)
}
