#' @title Skeleton pruning
#'
#' @description
#' Prunes a probability tree generated by \link{startskel}. Made for \link{skeleton}.
#'
#' @inheritParams skeleton
#' @param root Tree, generated from \link{startskel}.
#' @param copy Set to TRUE to preserve the original tree and return a pruned copy.
#' @param declare If TRUE prints how many nodes are cut by level of the tree.
#'
#' @returns If **copy = TRUE**, returns the pruned skeleton. Otherwise, alters the original object with no output.
#'
#' @details
#' For a node w, whose children are leaves, removes the children if:
#'  - both don't have enough occurrences to be significant.
#'  - both have the same prohibited transitions.
#'
#' Starts from the second to last level of the tree.
#'
#' @export

sculptskeleton = function(root, Nmin, copy=F, declare = F){
  if(copy) skel = Clone(root)
  else skel = root
  nodes = Traverse(skel,'level')
  levels = sapply(nodes, function(node) node$level)
  d = skel$height
  for(l in (d-1):1){
    selected = nodes[levels==l]
    to_prune = selected[sapply(selected, function(node) should.you.cut(node, Nmin))]
    if(declare) print(paste0("Level ", l, ', ',length(to_prune),' nodes to prune'))
    lapply(to_prune, function(parent) parent$children = NULL)
  }
  if(copy) return(skel)
}
